<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/4/14
 * Time: 23:22
 */
namespace app\modules\client\controllers;

use yii\web\Controller;
use Yii;

class CommonController extends Controller
{
    public $userId;
    public $userName;
    public $level;
    public $wxUser;
    public $userInfo;

    public function beforeAction($action)
    {

        //第一步获取session是否存在
        if(!$this->getUserSession()){
            //如果session不存在的话 , 我们判断cookie是否存在
            //有的话通过cookie生成session
        }
        //var_dump($this->userName);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 读取session并赋值给user
    */
    private function getUserSession()
    {
        $session = Yii::$app->session;
        $this->wxUser = $session->get("wxUser");
        $this->userInfo = $session->get("userInfo");
        return $this->userId;
    }

}